org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.1-SNAPSHOT
project.libs.versions.iteminteractions=26.1.5
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Fancy storage for fancy folks.
mod.group=fuzs.bagofholding
mod.id=bagofholding
mod.license=MPL-2.0
mod.name=Bag Of Holding
mod.version=26.1.3

dependencies.common.iteminteractions=embedded
dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=593996
distributions.curseforge.slug=bag-of-holding
distributions.github.slug=bag-of-holding
distributions.modrinth.id=qbqWvc0D
distributions.modrinth.slug=bag-of-holding

environments.client=required
environments.server=required
